apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: nginx
spec:
  containers: 
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
        - containerPort: 443
