apiVersion: v1
kind: Namespace
metadata:
  name: backend-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend-team
  name: backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rishavmehra/backend-bun
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend-team
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
